# Generated by Django 4.2.9 on 2024-01-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'PvM'), (2, 'PvP'), (3, 'Skilling'), (4, 'Questing'), (5, 'Speedrunning')], default=0),
        ),
    ]
