# Generated by Django 4.2.9 on 2024-01-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'PvM'), (2, 'PvP'), (3, 'Skilling'), (4, 'Questing')], default=0),
        ),
    ]
