# Generated by Django 4.2.9 on 2024-01-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_post_status_alter_post_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('None', 'None'), ('PvM', 'PvM'), ('PvP', 'PvP'), ('Skilling', 'Skilling'), ('Questing', 'Questing')], default='None'),
        ),
    ]
