# Generated by Django 4.2.9 on 2024-01-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('none', 'None'), ('pvm', 'PvM'), ('pvp', 'PvP'), ('skilling', 'Skilling'), ('questing', 'Questing')], default='none'),
        ),
    ]
